### ISSUE TITLE
Error during lifting

### ISSUE THREAD

**Issue by ShepelievD** [KSDaemon/sails-hook-sequelize#45]
Got the following error while lifted the app:
```
Executing (default): SELECT schema_name FROM information_schema.schemata WHERE schema_name <> 'information_schema' AND schema_name != 'public' AND schema_name !~ E'^pg_';
Executing (default): SELECT schema_name FROM information_schema.schemata WHERE schema_name <> 'information_schema' AND schema_name != 'public' AND schema_name !~ E'^pg_';
Executing (default): SELECT schema_name FROM information_schema.schemata WHERE schema_name <> 'information_schema' AND schema_name != 'public' AND schema_name !~ E'^pg_';
/Users/shepeliev/projects/rentloop-api/node_modules/sails/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
  at /Users/shepeliev/projects/rentloop-api/node_modules/sails/node_modules/async/lib/async.js:43:36
  at /Users/shepeliev/projects/rentloop-api/node_modules/async-listener/glue.js:188:31
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:218:9)
```

Please, need help ASAP 🙏

**Comment by KSDaemon** [comment]
Hi @ShepelievD! Well, what i can see from your log, this problem is not related to sequelize hook, AFAIU.

**Comment by KSDaemon** [comment]
Take a look at tests. There is v012, v1.0 tests there. And everywhere it is working as expected.
