### ISSUE TITLE
Sails lift hook load fail

### ISSUE THREAD

**Issue by Karnith** [KSDaemon/sails-hook-sequelize#47]
Sails version: 1.0.0-42
sails-hook-sequelize: 1.1.1

Sails fails on lift.

log:
Using default connection named default
verbo: Thu, 14 Dec 2017 17:48:42 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules\sequelize\lib\sequelize.js:236:13
Exposing Sequelize and Sequelize connections globally
error: A hook (`sequelize`) failed to load!
verbo: Loading model 'Titles'
verbo: sockets hook loaded successfully. (34ms)
verbo: Lowering sails...
error: Failed to lift app: TypeError: Cannot read property 'connection' of undefined
    at Hook.defineModels (E:\c2c-apiProject\node_modules\sails-hook-sequelize\index.js:112:51)
    at Hook.wrapper [as defineModels] (E:\c2c-apiProject\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at sails.modules.loadModels (E:\c2c-apiProject\node_modules\sails-hook-sequelize\index.js:42:22)
    at E:\c2c-apiProject\node_modules\sails\lib\hooks\moduleloader\index.js:326:18
    at E:\c2c-apiProject\node_modules\sails\lib\hooks\moduleloader\index.js:622:14
    at helpBuildDictionary (E:\c2c-apiProject\node_modules\include-all\lib\help-build-dictionary.js:135:10)
    at Function.module.exports.optional (E:\c2c-apiProject\node_modules\include-all\index.js:67:10)
    at E:\c2c-apiProject\node_modules\sails\lib\hooks\moduleloader\index.js:314:20
    at helpBuildDictionary (E:\c2c-apiProject\node_modules\include-all\lib\help-build-dictionary.js:135:10)
    at Function.module.exports.optional (E:\c2c-apiProject\node_modules\include-all\index.js:67:10)
    at Hook.loadModels (E:\c2c-apiProject\node_modules\sails\lib\hooks\moduleloader\index.js:304:18)
    at Hook.wrapper [as loadModels] (E:\c2c-apiProject\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at Hook.reload (E:\c2c-apiProject\node_modules\sails-hook-sequelize\index.js:36:34)
    at Hook.wrapper [as reload] (E:\c2c-apiProject\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at Hook.initialize (E:\c2c-apiProject\node_modules\sails-hook-sequelize\index.js:21:18)
    at Hook.wrapper [as initialize] (E:\c2c-apiProject\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at E:\c2c-apiProject\node_modules\sails\lib\hooks\index.js:106:18
    at E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:421:16
    at processQueue (E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:1565:20)
    at taskComplete (E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:1588:9)
    at E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:1612:17
    at E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:906:16
    at Hook.loadModules (E:\c2c-apiProject\node_modules\sails\lib\hooks\index.js:156:14)
    at Hook.wrapper [as loadModules] (E:\c2c-apiProject\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at modules (E:\c2c-apiProject\node_modules\sails\lib\hooks\index.js:83:25)
    at runTask (E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:1621:13)
    at E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:1559:13
    at processQueue (E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:1569:13)
    at Object.auto (E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:1555:5)
    at Hook.load (E:\c2c-apiProject\node_modules\sails\lib\hooks\index.js:77:13)
    at Hook.wrapper [as load] (E:\c2c-apiProject\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at loadHook (E:\c2c-apiProject\node_modules\sails\lib\app\private\loadHooks.js:208:17)
    at E:\c2c-apiProject\node_modules\sails\lib\app\private\loadHooks.js:330:13
    at E:\c2c-apiProject\node_modules\sails\node_modules\async\dist\async.js:3083:16

**Comment by Karnith** [comment]
update - when there isn't a model created sails lifts and loads sequalize hook. When a model has been created, it is then that teh hook fails to load.

**Comment by KSDaemon** [comment]
Hi @Karnith ! I think you have some misconfiguration of datastores...
I've just updates sails to 1.0.0−42 in tests — and everything works as expected. Take a look there!
